name: Trigger Shared Build (Java)

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Choose stage'
        required: true
        type: choice
        options: [dev, uat]

jobs:
  trigger-build:
    uses: sumersovitkargit/UBS_CI/.github/workflows/shared-build.yml@main
    with:
      environment-name: java
      stage: ${{ github.event.inputs.stage }}
